### ISSUE TITLE
Data distribution in pretraining dataset

### ISSUE THREAD

**Issue by leannmlindsey** [MAGICS-LAB/DNABERT_2#101]
Hello, 

In your appendix you list the genomes that you used for training and the number of nucleotides. From that can I assume that you didn't do anything to further balance the dataset (ie use more samples from human than other species.)

In other words, would the number of nucleotides of a specific genome divided by the total number of nucleotides in the training set be the appropriate percentage of that species in the dataset?

Thank you
LeAnn

**Comment by Zhihan1996** [comment]
Yes, we did not do any data balancing, so the the number of nucleotides of a specific genome divided by the total number of nucleotides in the training set is the appropriate percentage of that species in the dataset.
