### ISSUE TITLE
cls_token

### ISSUE THREAD

**Issue by lilian-zh** [MAGICS-LAB/DNABERT_2#115]
Thank you for your excellent work. Could you please explain how we can extract the cls_token? 
I appreciate your assistance.

**Comment by Zhihan1996** [comment]
Sorry for the late reply! Can you share your use case in more details? If you are looking for DNA embedding, please use the average of all the token embedding. In general, the CLS token embedding is not meaningful.

**Comment by lilian-zh** [comment]
Okay, will use the mean pooling. Thank you.
