### ISSUE TITLE
DNA Representation

### ISSUE THREAD

**Issue by ChangShaole** [MAGICS-LAB/DNABERT_2#117]
Hi, I wanna use your model to get the DNA representation. The DNAs are all homo sapiens'.
As I know, there are two optional models, DNABERT-2 and DNABERT-S. So I wanna know which model is better for this task.

**Comment by Zhihan1996** [comment]
Hi, DNABERT-S is designed for DNA embedding that distinguishes species. DNABERT-2 is a more general model. In you case I think DNABERT-2 is more suitable.
