### ISSUE TITLE
Specific processes for pre-training

### ISSUE THREAD

**Issue by yuyadanyadan** [MAGICS-LAB/DNABERT_2#118]
Thank you for your work. I want to know the specific  processes for pre-training. I can run the following code from https://github.com/huggingface/transformers/tree/main/examples/pytorch/language-modeling.
python run_mlm.py \
    --model_name_or_path FacebookAI/roberta-base \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --output_dir /tmp/test-mlm

However, how can my own DNA sequences be processed into a type that this code will recognize? What form of pre-training data does the code need? How do I process it into this form? Thank you very much and I look forward to hearing from you.

**Comment by Zhihan1996** [comment]
Hey,

For the pre-training data, you should create a txt file where each line is a separate DNA sequenece (in upper case). To achieve it, you can just use a simple python script to remove all the headers in a FASTA/FA file. 

For pre-training, just add `--config_name zhihan1996/DNABERT-2-117M`,  `--tokenizer_name zhihan1996/DNABERT-2-117M` and remove the `model_name_or_path`. Also, change the batch size, learning rates, etcs accordingly.

**Comment by yuyadanyadan** [comment]
Thank you!  And I wish you all the best

**Comment by yuyadanyadan** [comment]
Sorry to bother you again. 
I trained my own data with next code. The run_mlm.py is from  https://github.com/huggingface/transformers/tree/main/examples/pytorch/language-modeling.

python run_mlm.py
--config_name /share/home/yuyadan/workspace/DNABERT_2/DNABERT-2-117M \
--tokenizer_name /share/home/yuyadan/workspace/DNABERT_2/DNABERT-2-117M \
--train_file /share/home/yuyadan/workspace/DNABERT_2/pre_train/data/train.txt \
--validation_file /share/home/yuyadan/workspace/DNABERT_2/pre_train/data/dev.txt \
--trust_remote_code True \
--per_device_train_batch_size 8 \
--per_device_eval_batch_size 8 \
--do_train \
--do_eval \
--output_dir /share/home/yuyadan/workspace/DNABERT_2/pre_train/output


But, I got the following error.

10/24/2024 11:10:46 - INFO - __main__ - Training new model from scratch
Traceback (most recent call last):
  File "run_mlm.py", line 692, in <module>
    main()
  File "run_mlm.py", line 445, in main
    model = AutoModelForMaskedLM.from_config(config, trust_remote_code=model_args.trust_remote_code)
  File "/share/home/yuyadan/workspace/env/transformers-main/src/transformers/models/auto/auto_factory.py", line 434, in from_config
    cls.register(config.__class__, model_class, exist_ok=True)
  File "/share/home/yuyadan/workspace/env/transformers-main/src/transformers/models/auto/auto_factory.py", line 584, in register
    raise ValueError(
ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers.models.bert.configuration_bert.BertConfig'> and you passed <class 'transformers_modules.DNABERT-2-117M.configuration_bert.BertConfig'>. Fix one of those so they match!


This could be a problem of conflicting versions of transformers. But,  run_mlm.py requires that the version of transformers must be 4.46.0.dev0. This conflicts with the 4.28.0 required in DNABERT-2-117M. I would like to ask what are the ways to solve the problem, looking forward to your reply. Thank you so much!
