### ISSUE TITLE
Question About DNAbert2 Pre-training Dataset Sources

### ISSUE THREAD

**Issue by yanghu819** [MAGICS-LAB/DNABERT_2#124]
I am attempting to reproduce the complete training procedure of DNAbert2. However, I've noticed that the pre-training dataset lacks source annotations (e.g., whether sequences are from ENCODE or viral genomes). This information is crucial for understanding and validating the model training process.

1. How can I identify the sources of the pre-training data?
2. Is there documentation or a paper detailing the data collection process?
3. Are there any metadata files accompanying the dataset that might contain this information?

**Comment by Zhihan1996** [comment]
Sorry for the late reply! Unfortunately we did not maintain any metadata accompanying the dataset. As discussed in the paper, all the genomes are acquired from GenBank through NCBI. We extract the whole genome and split them into 1000bp segments. The detailed species are listed in the paper appendix.
