### ISSUE TITLE
Results obtained in the original paper

### ISSUE THREAD

**Issue by Zehui127** [MAGICS-LAB/DNABERT_2#127]
Dear Team,

In the original paper https://arxiv.org/pdf/2306.15006, the results presented in table 6 and table 9 are inconsistent. I wonder which one is the correct results? For example, in table 6 the **MCC** in Transcription Factor Prediction (Mouse) of DNABERT2 is 56.76, while in table 9, it is 81.60. It was a bit confusing. 

Really appreciate if you could help to resolve this issue. It seems that most of the following-up work is using the results presented in table 6, so it is important to clarify if this is not the case. 

Best,
Zehui Li

**Comment by Zhihan1996** [comment]
Hey Zehui,

Thanks for indicating this! We mistakenly present different metrics in these two tables. The lower ones in Table 6 are **MCC** and the higher ones in Table 9 are **F1**.
