### ISSUE TITLE
Clarification on Pre-training: BertForMaskedLM vs BertModelForMaskedLM

### ISSUE THREAD

**Issue by RobinLi7** [MAGICS-LAB/DNABERT_2#128]
In the Pre-training step, there is no BertModelForMaskedLM from https://huggingface.co/zhihan1996/DNABERT-2-117M/blob/main/bert_layers.py.
However, there is a BertForMaskedLM in the file. Is this a typographical error or are you referring to something else?

**Comment by Zhihan1996** [comment]
Thanks for asking. It was a typo. I referred to `BertForMaskedLM `.
