### ISSUE TITLE
environment about torch version

### ISSUE THREAD

**Issue by xueleecs** [MAGICS-LAB/DNABERT_2#70]
Thanks for sharing the code. I've tried many versions of torch and still get errors.
There's also TypeError("dot() got an unexpected keyword argument 'trans_b'"). Please tell me the possible solution.
Thank you so much.

**Comment by Zhihan1996** [comment]
Hey,

Can you please try `pip uninstall triton`? This is the triton package and installation of the package can be very tricky depending on your hardware.
