### ISSUE TITLE
Discuss a question about k-mer

### ISSUE THREAD

**Issue by xueleecs** [MAGICS-LAB/DNABERT_2#73]
I found out through dubug that this pre-trained model is rounded up by 4 bases. Can I change it to 128 bases by changing a few parameters. Do I need to re-pre-train the model?

**Comment by Zhihan1996** [comment]
Sorry for this late reply! For the maximum sequence length, if you are doing fine-tuning, you can change it to whatever value you want as long as your GPU memory is enough to host it.
