### ISSUE TITLE
Cannot Reproduce DNA-BERT2‘s Result

### ISSUE THREAD

**Issue by KatarinaYuan** [MAGICS-LAB/DNABERT_2#86]
Hi,
    I try to run the command in `./DNABERT_2/finetune/scripts/run_dnabert2.sh` and get the following results. However, it cannot match the reported ones in DNA-BERT2's paper.
    
    
![Screen Shot 2024-05-07 at 10 44 19 PM](https://github.com/MAGICS-LAB/DNABERT_2/assets/43512683/97c9232b-7c42-4755-b081-549898a0feca)

**Comment by Zhihan1996** [comment]
Can you specify the hyperparameters you are using? For example, this scripts expect 4 GPUs for a suitable batch size and training steps.
