### ISSUE TITLE
GUE+ datasets?

### ISSUE THREAD

**Issue by leannmlindsey** [MAGICS-LAB/DNABERT_2#87]
I do not see that you have made the GUE+ datasets available at the link for the GUE.zip download.  Are they available in another location?

**Comment by fma231** [comment]
could you also please provide the hyperparameter details used for their finetuning? I could reproduce the results on GUE but not GUE+, with hyperparameters used in the paper

**Comment by yangzhao1230** [comment]
> could you also please provide the hyperparameter details used for their finetuning? I could reproduce the results on GUE but not GUE+, with hyperparameters used in the paper

> could you also please provide the hyperparameter details used for their finetuning? I could reproduce the results on GUE but not GUE+, with hyperparameters used in the paper


> could you also please provide the hyperparameter details used for their finetuning? I could reproduce the results on GUE but not GUE+, with hyperparameters used in the paper


> could you also please provide the hyperparameter details used for their finetuning? I could reproduce the results on GUE but not GUE+, with hyperparameters used in the paper


> could you also please provide the hyperparameter details used for their finetuning? I could reproduce the results on GUE but not GUE+, with hyperparameters used in the paper


Hi @fma231 ，

Could I know how you conducted the experiment regarding enhancer interaction? There are two input sequences, but the paper does not specify the exact approach.
