### ISSUE TITLE
Random issues still come up in use

### ISSUE THREAD

**Issue by josecar24** [MAGICS-LAB/DNABERT_2#95]
Hello Dr. ZHOU(@Zhihan1996),

For the random problem, I found the problem still exists for same DNA sequence if I reload the model by running the first code cell. For instance, If I run the second code cell twice in a row directly after the model is loaded. The output tensor will be consistent due to 'model = model.eval()' as you suggested. But if I run the first code cell again between running the second and third code cells, and the random problem will reappear (and not be solved with my addition of model.eval after model loaded in code cell one).
Is that designed to be different outcome for operations between batches? Is there any possible solution to keep the output tensor from the same DNA sequence always the same please? Appreciate again!

<img width="812" alt="截屏2024-06-17 下午12 51 41" src="https://github.com/MAGICS-LAB/DNABERT_2/assets/112451709/0512e3a7-f2a7-4e2b-a866-48974044a8f6">

**Comment by GUMI-QXP** [comment]
Hello, I have also encountered this problem. Have you resolved it?
