### ISSUE TITLE
Attention error

### ISSUE THREAD

**Issue by HelloWorldLTY** [MAGICS-LAB/DNABERT_2#96]
Hi, I tried to install the model without triton (which was reported in previous issues), and I received such an error:

```
assert q.is_cuda and k.is_cuda and v.is_cuda
```

Would you please share your yml file for the environment to  set up DNABERT? I think it will be really helpful. Thanks a lot.

**Comment by Zhihan1996** [comment]
please try `pip uninstall triton` and run the code again.
